# Generated by Django 3.2.9 on 2021-11-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa', '0002_alter_device_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
