# Generated by Django 3.2.9 on 2021-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_2fa', '0003_device_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='counter_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
